appId: kiwi.kyle.dmx.pptx
files:
  - from: dist
    to: dist
    filter:
      - main/**/*
      - renderer/**/*
  - filter:
      - package.json

win:
  target:
  - default
  publisherName: Kyle Hensel
  publish: null # FIXME: enable this once stable

mac:
  target:
  - default
  category: public.app-category.utilities
  publish: null # FIXME: enable this once stable
