appId: kiwi.kyle.dmx.pptx
productName: DMX PowerPoint
extends: null

files:
  - filter:
      - dist/**/*
      - package.json

# so that it loads icon.png
directories:
  buildResources: public

win:
  target:
    - default
  publisherName: Kyle Hensel
  publish: null # FIXME: enable this once stable

mac:
  target:
    - default
  category: public.app-category.utilities
  publish: null # FIXME: enable this once stable
