---
root: true
env:
  es6: true
  node: true

extends:
- airbnb-base
- plugin:node/recommended
- plugin:vue/recommended

parser: vue-eslint-parser

settings:
  import/core-modules: [ electron ]
  node:
    allowModules:
    - electron

rules:
  max-len: warn
  no-console: 'off'
  no-await-in-loop: 'off'
  no-restricted-syntax: 'off'
  guard-for-in: 'off'

  prefer-destructuring: warn
  prefer-object-spread: warn
  no-warning-comments: warn

  import/no-unresolved: 'off'
  import/prefer-default-export: 'off'
  indent: 'off'
  node/no-unsupported-features/es-syntax: 'off'
  vue/html-quotes:
  - 2
  - single
